FROM centos:7.4.1708


RUN yum install -y epel-release && \
yum install -y app-protect && \
yum install -y app-protect-attack-signatures && \
cp nginx.conf /etc/nginx/nginx.conf.orig && \
mkdir -p /root

COPY nginx.conf /etc/nginx/
COPY entrypoint.sh /root
COPY log-default.json /etc/nginx

CMD ["/root/entrypoint.sh"]
